export const MOVE_CHARACTER_RIGHT = 'MOVE_CHARACTER_RIGHT';
export const MOVE_CHARACTER_LEFT = 'MOVE_CHARACTER_LEFT';
export const MOVE_CHARACTER_TOP = 'MOVE_CHARACTER_TOP';
export const MOVE_CHARACTER_BOTTOM = 'MOVE_CHARACTER_BOTTOM';
export const MOVE_CHARACTER = 'MOVE_CHARACTER';
